name: Linux Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    env:
      ALTERNATE_CC: gcc-8
      ALTERNATE_CXX: g++-8
      MAKE_THREADS: 3
    
    cache:
      directories:
        - OpenBLAS-0.3.4
        - dlib-19.16
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install gcc-8 g++-8 gcc-8-multilib g++-8-multilib
    
    - name: Cache OpenBLAS
      uses: actions/cache@v3
      with:
        path: OpenBLAS-0.3.4
        key: openblas-0.3.4
    
    - name: Build OpenBLAS
      run: |
        if [ ! -f "OpenBLAS-0.3.4/Makefile" ]; then 
          wget https://github.com/xianyi/OpenBLAS/archive/v0.3.4.tar.gz
          tar xf v0.3.4.tar.gz
        fi
        cd OpenBLAS-0.3.4
        make FC=gfortran USE_THREAD=0 -j $MAKE_THREADS > /dev/null
        sudo make PREFIX=/usr/local install
        cd ..
    
    - name: Cache dlib
      uses: actions/cache@v3
      with:
        path: dlib-19.16
        key: dlib-19.16
    
    - name: Build dlib
      run: |
        if [ ! -f "dlib-19.16/CMakeLists.txt" ]; then
          wget https://github.com/davisking/dlib/archive/v19.16.tar.gz
          tar xf v19.16.tar.gz
        fi
        mkdir -p dlib-19.16/build
        cd dlib-19.16/build
        cmake .. -DBUILD_SHARED_LIBS=ON -DDLIB_JPEG_SUPPORT=OFF -DDLIB_PNG_SUPPORT=OFF -DDLIB_NO_GUI_SUPPORT=ON
        cmake --build . --config Release -- -j $MAKE_THREADS
        sudo make install
        sudo ldconfig
        cd ../..
    
    - name: Prepare build
      run: |
        cp -r ./sampml/sampml ./examples/anti-aimbot/plugin/lib
        cp -r ./dlib-19.16/dlib ./examples/anti-aimbot/plugin/lib
        sudo ln -s /usr/include/asm-generic /usr/include/asm
    
    - name: Build training tools
      run: |
        cd examples/anti-aimbot/training
        make CXX=$ALTERNATE_CXX -j $MAKE_THREADS
        time ./transformer
        time ./analyzer
        time ./svm
        time ./rf
        time ./dnn
        time ./combined
        time ./standalone_tester ./data/avoiding_detection.dat
    
    - name: Build plugin
      run: |
        cd examples/anti-aimbot/plugin
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$ALTERNATE_CC -DCMAKE_CXX_COMPILER=$ALTERNATE_CXX
        cmake --build . -- -j $MAKE_THREADS
    
    - name: Package artifacts
      run: |
        mkdir -p package/plugins/anti-aimbot/models package/pawno/include package/filterscripts
        cp -f examples/anti-aimbot/plugin/build/AntiAimbot.so package/plugins/anti-aimbot/
        cp -rf examples/anti-aimbot/training/models package/plugins/anti-aimbot/
        cp -rf examples/anti-aimbot/filterscripts package/
        cp -rf examples/anti-aimbot/include package/pawno/
        tar czf antiaimbot-linux.tar.gz package
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: antiaimbot-linux
        path: antiaimbot-linux.tar.gz
